"""updated user model

Revision ID: 10002778a9e9
Revises: 59348e93e570
Create Date: 2026-01-04 02:51:30.778113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10002778a9e9'
down_revision: Union[str, None] = '59348e93e570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('approving_manager_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('reporting_manager_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user', ['reporting_manager_id'], ['id'])
    op.create_foreign_key(None, 'user', 'user', ['approving_manager_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'reporting_manager_id')
    op.drop_column('user', 'approving_manager_id')
    # ### end Alembic commands ###
