"""updated logs model

Revision ID: 3890390d83c8
Revises: 8c98f8fcaaa3
Create Date: 2026-01-03 23:48:01.272563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3890390d83c8'
down_revision: Union[str, None] = '8c98f8fcaaa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'data')
    op.drop_constraint('organization_member_user_id_fkey', 'organization_member', type_='foreignkey')
    op.create_foreign_key(None, 'organization_member', 'user', ['user_id'], ['id'])
    
    # Migrate task_id to issue_id
    op.add_column('system_logs', sa.Column('issue_id', sa.Integer(), nullable=True))
    op.execute('UPDATE system_logs SET issue_id = task_id')
    op.alter_column('system_logs', 'issue_id', nullable=False)
    
    op.drop_constraint('system_logs_task_id_fkey', 'system_logs', type_='foreignkey')
    op.create_foreign_key(None, 'system_logs', 'issue', ['issue_id'], ['id'])
    op.drop_column('system_logs', 'task_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_logs', sa.Column('task_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'system_logs', type_='foreignkey')
    op.create_foreign_key('system_logs_task_id_fkey', 'system_logs', 'issue', ['task_id'], ['id'])
    op.drop_column('system_logs', 'issue_id')
    op.drop_constraint(None, 'organization_member', type_='foreignkey')
    op.create_foreign_key('organization_member_user_id_fkey', 'organization_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('issue', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
