"""updated issue model

Revision ID: 796b11556604
Revises: 3890390d83c8
Create Date: 2026-01-04 02:23:55.868547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '796b11556604'
down_revision: Union[str, None] = '3890390d83c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column as nullable first
    op.add_column('issue', sa.Column('time_estimate', sa.Numeric(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE issue SET time_estimate = 0 WHERE time_estimate IS NULL")
    # Now make it NOT NULL
    op.alter_column('issue', 'time_estimate', nullable=False, server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue', 'time_estimate')
    # ### end Alembic commands ###
