"""updated organization member and issue model

Revision ID: 8c98f8fcaaa3
Revises: e4ef2c7f2fd7
Create Date: 2026-01-03 01:38:54.517214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c98f8fcaaa3'
down_revision: Union[str, None] = 'e4ef2c7f2fd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invite_tokens', 'used')
    op.add_column('issue', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint('organization_member_user_id_fkey', 'organization_member', type_='foreignkey')
    op.create_foreign_key(None, 'organization_member', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organization_member', type_='foreignkey')
    op.create_foreign_key('organization_member_user_id_fkey', 'organization_member', 'user', ['user_id'], ['id'])
    op.drop_column('issue', 'data')
    op.add_column('invite_tokens', sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
