"""added new/updated models

Revision ID: b7cf6194f454
Revises: 0c16c0ee6bfa
Create Date: 2025-12-23 23:56:53.489157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7cf6194f454'
down_revision: Union[str, None] = '0c16c0ee6bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum types only if they don't exist (to avoid duplicate errors)
    conn = op.get_bind()
    
    # Helper function to check if enum exists
    def enum_exists(enum_name):
        result = conn.execute(sa.text("SELECT 1 FROM pg_type WHERE typname = :enum_name"), {"enum_name": enum_name})
        return result.fetchone() is not None
    
    # Create enum types only if they don't exist (to avoid duplicate enum errors)
    if not enum_exists('role'):
        op.execute(sa.text("CREATE TYPE role AS ENUM ('ADMIN', 'MANAGER', 'EMPLOYEE')"))
    
    if not enum_exists('userstatus'):
        op.execute(sa.text("CREATE TYPE userstatus AS ENUM ('ACTIVE', 'INACTIVE', 'BLOCKED')"))
    
    if not enum_exists('project_enum'):
        op.execute(sa.text("CREATE TYPE project_enum AS ENUM ('ACTIVE', 'INACTIVE', 'UPCOMING', 'DELAYED', 'COMPLETED')"))
    
    if not enum_exists('sprint_enum'):
        op.execute(sa.text("CREATE TYPE sprint_enum AS ENUM ('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'TRANSFERRED')"))
    
    if not enum_exists('issuestatus'):
        op.execute(sa.text("CREATE TYPE issuestatus AS ENUM ('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'HOLD')"))
    
    if not enum_exists('issue_type_enum'):
        op.execute(sa.text("CREATE TYPE issue_type_enum AS ENUM ('STORY', 'TASK', 'BUG', 'EPIC', 'SUBTASK', 'FEATURE', 'RELEASE', 'DOCUMENTATION', 'OTHER')"))
    
    # Create user table (always create, Alembic will handle if it already exists)
    # Use postgresql.ENUM with create_type=False since we create enums manually above
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', postgresql.ENUM('ADMIN', 'MANAGER', 'EMPLOYEE', name='role', create_type=False), nullable=False),
    sa.Column('story_point', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'BLOCKED', name='userstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    
    # Create project table
    op.create_table('project',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', postgresql.ENUM('ACTIVE', 'INACTIVE', 'UPCOMING', 'DELAYED', 'COMPLETED', name='project_enum', create_type=False), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create project_member table
    op.create_table('project_member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='u_project_user')
    )
    
    # Create sprint table
    op.create_table('sprint',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sprint_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', postgresql.ENUM('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'TRANSFERRED', name='sprint_enum', create_type=False), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create issue table
    op.create_table('issue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('story_point', sa.Integer(), nullable=True),
    sa.Column('status', postgresql.ENUM('TODO', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'HOLD', name='issuestatus', create_type=False), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('type', postgresql.ENUM('STORY', 'TASK', 'BUG', 'EPIC', 'SUBTASK', 'FEATURE', 'RELEASE', 'DOCUMENTATION', 'OTHER', name='issue_type_enum', create_type=False), nullable=False),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create system_logs table
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour_worked', sa.Numeric(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['issue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop tables in reverse order (respecting foreign key constraints)
    op.drop_table('system_logs')
    op.drop_table('issue')
    op.drop_table('sprint')
    op.drop_table('project_member')
    op.drop_table('project')
    op.drop_table('user')
